# Generated by Django 3.2 on 2021-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_profile'),
        ('users', '0004_auto_20210504_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_wishlist', to='blog.Product'),
        ),
    ]
