# Generated by Django 3.2 on 2021-05-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
    ]
