# Generated by Django 3.1.7 on 2021-05-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210501_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
