# Generated by Django 3.2 on 2021-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='testproduct'),
            preserve_default=False,
        ),
    ]
