# Generated by Django 3.2 on 2021-05-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
    ]
